------------------------------------------------
-- DDL Statements for Table "GADMIN"."CS_INSA_SOSOKCHG_M"
------------------------------------------------


CREATE TABLE "GADMIN"."CS_INSA_SOSOKCHG_M"  (
		  "INSA_NO" VARCHAR(6 OCTETS) NOT NULL ,
		  "SOSOKCHG_CD" VARCHAR(10 OCTETS) NOT NULL ,
		  "BIGO" VARCHAR(500 OCTETS) ,
		  "INSERT_ID" VARCHAR(200 OCTETS) ,
		  "INSERT_NAME" VARCHAR(200 OCTETS) ,
		  "INSERT_IP" VARCHAR(200 OCTETS) ,
		  "INSERT_DATE" TIMESTAMP ,
		  "INSERT_PGM" VARCHAR(200 OCTETS) ,
		  "UPDATE_ID" VARCHAR(200 OCTETS) ,
		  "UPDATE_NAME" VARCHAR(200 OCTETS) ,
		  "UPDATE_IP" VARCHAR(200 OCTETS) ,
		  "UPDATE_DATE" TIMESTAMP ,
		  "UPDATE_PGM" VARCHAR(200 OCTETS))
--		 IN "TS_COMMON_DAT" INDEX IN "TS_COMMON_IDX"
--		 ORGANIZE BY ROW;
		 IN "USERSPACE1"
		 ORGANIZE BY ROW;


COMMENT ON TABLE "GADMIN"."CS_INSA_SOSOKCHG_M" IS '[공통]인사소속변경관리';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."BIGO" IS '비고';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."INSA_NO" IS '인사사번';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."INSERT_DATE" IS '입력일시';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."INSERT_ID" IS '입력자ID';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."INSERT_NAME" IS '입력자 성명';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."INSERT_IP" IS '입력자IP';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."INSERT_PGM" IS '입력프로그램';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."SOSOKCHG_CD" IS '변경소속코드';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."UPDATE_DATE" IS '수정일시';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."UPDATE_ID" IS '수정자ID';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."UPDATE_NAME" IS '수정자 성명';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."UPDATE_IP" IS '수정자IP';

COMMENT ON COLUMN "GADMIN"."CS_INSA_SOSOKCHG_M"."UPDATE_PGM" IS '수정프로그램';


-- DDL Statements for Indexes on Table "GADMIN"."CS_INSA_SOSOKCHG_M"

SET NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GADMIN"."PK_CS_INSA_SOSOKCHG_M" ON "GADMIN"."CS_INSA_SOSOKCHG_M"
		("INSA_NO" ASC)

		COMPRESS NO
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GADMIN"."CS_INSA_SOSOKCHG_M"

ALTER TABLE "GADMIN"."CS_INSA_SOSOKCHG_M"
	ADD CONSTRAINT "PK_CS_INSA_SOSOKCHG_M" PRIMARY KEY
		("INSA_NO");
